export const metadata = {
  title: 'Terms of Service | Prompt4life',
  description: 'Read the terms and conditions for using the Prompt4life AI prompt marketplace.',
}

export default function TermsPage() {
  return (
    <div className="w-full flex flex-col items-center">
      <section className="w-full bg-muted/30 border-b py-16 px-5 flex flex-col items-center text-center">
        <h1 className="text-4xl font-black tracking-tighter mb-4">Terms of Service</h1>
        <p className="text-muted-foreground max-w-2xl">
          Last Updated: April 10, 2026
        </p>
      </section>

      <div className="w-full max-w-4xl px-5 py-20 prose prose-slate dark:prose-invert">
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using the Prompt4life marketplace ("Platform"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Platform.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          Prompt4life provides a marketplace for users to discover, share, and utilize artificial intelligence prompts. We do not provide the AI models themselves (e.g., ChatGPT, Midjourney), but rather the instructional text used to interact with them.
        </p>

        <h2>3. User Accounts</h2>
        <p>
          To access certain features, you may be required to register for an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.
        </p>

        <h2>4. Content Guidelines</h2>
        <p>
          Users may submit prompts to the Platform. By submitting content, you represent that you have the right to share it and that it does not violate any third-party rights or applicable laws. We reserve the right to remove any content that:
        </p>
        <ul>
          <li>Is illegal, harmful, or offensive.</li>
          <li>Violates the terms of use of the AI models the prompts are intended for.</li>
          <li>Infringes on intellectual property rights.</li>
          <li>Is of low quality or non-functional.</li>
        </ul>

        <h2>5. Points & Reputation System</h2>
        <p>
          The Platform uses a points and reputation system for rewarding community engagement. Points can be earned through community contributions, prompt submissions, and platform participation. Points have no cash value and cannot be transferred, sold, or redeemed for real-world currency.
        </p>

        <h2>6. Limitation of Liability</h2>
        <p>
          Prompt4life is provided "as is" without any warranties. We are not responsible for the results generated by the AI models when using prompts from our platform.
        </p>

        <h2>7. Changes to Terms</h2>
        <p>
          We reserve the right to modify these terms at any time. Your continued use of the Platform after changes are posted constitutes your acceptance of the new terms.
        </p>

        <h2>8. Contact Us</h2>
        <p>
          If you have any questions about these Terms, please contact us at support@prompt4life.com.
        </p>
      </div>
    </div>
  )
}
